replicaCount: 1

image:
  repository: busybox
  tag: latest

namespace: bosster-test

env:
  DB_HOST: "bosster-test-aurora.cluster-crio00c4sjtt.eu-west-1.rds.amazonaws.com:5432"
  RAW_BUCKET: "bosster-test-uploads-460474851007"
  # INTENTIONAL DRIFT: deployed uses bosster-test-analytics, Git says bosster-test-orders
  QUEUE_URL: "https://sqs.eu-west-1.amazonaws.com/460474851007/bosster-test-orders"
